### ISSUE TITLE
Module is great, remapping from legacy site tools?

### ISSUE THREAD

**Issue by surfjedi** [silverstripe-australia-archive/link-mapping#2]
This module is great, thanks!

Any ideas on a tool to just crawl an old site that is being migrated to SS, and produce a spreadsheet to upload into this module?  
I have a massive site that is being rebuilt and i need to redirect all the old legacy links.

Thanks in advance

**Comment by nglasl** [comment]
This module has been superceded by the misdirection module, and is therefore no longer maintained.

https://github.com/nglasl/silverstripe-misdirection
