### ISSUE TITLE
Are mapped link URLs with query strings no longer supported?

### ISSUE THREAD

**Issue by sheadawson** [silverstripe-australia-archive/link-mapping#5]
I am updating an old 2.4 site which has a whole lot of MappedLink redirects from urls like /page.php?section=240. It seems this module used to redirect urls with querystrings but not anymore? Any reason why or is there a new way of doing it or?

This is the main bit of code that appears to have been removed from LinkMappingFrontController at some point before you created current new repo

```
if ($request->requestVars()){
    $queryString = '?';
    foreach($request->requestVars() as  $key => $value) {
	if($key !='url'){$queryString .=$key.'='.$value.'&';}
    }
    $queryString =  rtrim($queryString,'&');
}
$link = ($queryString != '?' ? $request->getURL().$queryString : $request->getURL());
```
Thanks,

Shea

**Comment by nglasl** [comment]
This module has been superceded by the misdirection module, and is therefore no longer maintained.

https://github.com/nglasl/silverstripe-misdirection
