### ISSUE TITLE
breaks 404 system

### ISSUE THREAD

**Issue by asecondwill** [silverstripe-australia-archive/link-mapping#9]
Hi, 

Unfortunately this module seems to be breaking silverstripe 404 system - urls that do not map to pages are being either redirected to the home page or to the /home/page url
eg:
/not/found -> /home/found
/not-found -> /

I'm testing this on a fresh SS install, 3.1.stable with no other modules

Thanks

Will

**Comment by nglasl** [comment]
This module has been superceded by the misdirection module, and is therefore no longer maintained.

https://github.com/nglasl/silverstripe-misdirection
